sudo: required
services:
- docker
language: node_js
install:
- npm install -g codecov
- npm install
node_js:
- "node"
script:
- docker-compose -f docker-compose.dev.yml up -d
- npm run build
- npm run coverage:ci
- codecov
