version: '3.1'
services:
  uvpm:
    container_name: uvpm
    build:
      context: .
      dockerfile: docker/uvpm.Dockerfile
    ports:
      - 3000:3000
    links:
      - mongodb
      - elasticsearch
      - elasticsearch2
    depends_on:
      - mongodb
      - elasticsearch
      - elasticsearch2
    environment:
      - DB_URL=mongodb://mongodb:27017/uvpm
      - ES_URL=elasticsearch:9200
    networks:
      - server


  mongodb:
    image: mongo:3.6.1
    container_name: uv-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
        - 27017:27017
    command: mongod
    networks:
      - server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: uvpm-elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
      - server

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: uvpm-elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  mongodb:
  mongodb_config:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
  server:
